# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32db750ddbf2ec6778dbf3ee2dbb122a90ec1197053b41e2dcfb74d4435d26c78502ae56f1304c7b75919d6498ed998a1a85bb36c01d9b2b39b17f446ceece9c

test:
  secret_key_base: d9bbba38b65e0779e023f484a69441bf51411b85464649ff5ed3ef52efa3dc824feeda2bfb38b45cf40c4abc07803050efb654454bf5b9dc07771668be33487c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
